//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceWeekDays.Console.Client.ServiceReferenceWeekDays {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWeekDays.IServiceWeekDays")]
    public interface IServiceWeekDays {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeekDays/GetDayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IServiceWeekDays/GetDayOfWeekInBulgarianResponse")]
        string GetDayOfWeekInBulgarian(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeekDays/GetDayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IServiceWeekDays/GetDayOfWeekInBulgarianResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekInBulgarianAsync(System.DateTime dateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWeekDaysChannel : WcfServiceWeekDays.Console.Client.ServiceReferenceWeekDays.IServiceWeekDays, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWeekDaysClient : System.ServiceModel.ClientBase<WcfServiceWeekDays.Console.Client.ServiceReferenceWeekDays.IServiceWeekDays>, WcfServiceWeekDays.Console.Client.ServiceReferenceWeekDays.IServiceWeekDays {
        
        public ServiceWeekDaysClient() {
        }
        
        public ServiceWeekDaysClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWeekDaysClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWeekDaysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWeekDaysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeekInBulgarian(System.DateTime dateTime) {
            return base.Channel.GetDayOfWeekInBulgarian(dateTime);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekInBulgarianAsync(System.DateTime dateTime) {
            return base.Channel.GetDayOfWeekInBulgarianAsync(dateTime);
        }
    }
}
