-- MySQL Script generated by MySQL Workbench
-- 10/04/15 17:11:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Universities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Universities` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facilities` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(200) NOT NULL COMMENT '',
  `Universities_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_table1Facilities_Universities_idx` (`Universities_id` ASC)  COMMENT '',
  CONSTRAINT `fk_table1Facilities_Universities`
    FOREIGN KEY (`Universities_id`)
    REFERENCES `mydb`.`Universities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(150) NOT NULL COMMENT '',
  `Facilities_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Departments_Facilities1_idx` (`Facilities_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Departments_Facilities1`
    FOREIGN KEY (`Facilities_id`)
    REFERENCES `mydb`.`Facilities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(200) NOT NULL COMMENT '',
  `Departments_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Professors_Departments1_idx` (`Departments_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`Departments_id`)
    REFERENCES `mydb`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(50) NOT NULL COMMENT '',
  `Titlescol` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(100) NOT NULL COMMENT '',
  `Departments_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Courses_Departments1_idx` (`Departments_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`Departments_id`)
    REFERENCES `mydb`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(200) NOT NULL COMMENT '',
  `Number` INT NOT NULL COMMENT '',
  `Facilities_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Students_Facilities1_idx` (`Facilities_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Students_Facilities1`
    FOREIGN KEY (`Facilities_id`)
    REFERENCES `mydb`.`Facilities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors_has_Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors_has_Titles` (
  `Professors_id` INT NOT NULL COMMENT '',
  `Titles_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Professors_id`, `Titles_id`)  COMMENT '',
  INDEX `fk_Professors_has_Titles_Titles1_idx` (`Titles_id` ASC)  COMMENT '',
  INDEX `fk_Professors_has_Titles_Professors1_idx` (`Professors_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Professors_has_Titles_Professors1`
    FOREIGN KEY (`Professors_id`)
    REFERENCES `mydb`.`Professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_has_Titles_Titles1`
    FOREIGN KEY (`Titles_id`)
    REFERENCES `mydb`.`Titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors_has_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors_has_Courses` (
  `Professors_id` INT NOT NULL COMMENT '',
  `Courses_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Professors_id`, `Courses_id`)  COMMENT '',
  INDEX `fk_Professors_has_Courses_Courses1_idx` (`Courses_id` ASC)  COMMENT '',
  INDEX `fk_Professors_has_Courses_Professors1_idx` (`Professors_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Professors_has_Courses_Professors1`
    FOREIGN KEY (`Professors_id`)
    REFERENCES `mydb`.`Professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_has_Courses_Courses1`
    FOREIGN KEY (`Courses_id`)
    REFERENCES `mydb`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses_has_Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses_has_Students` (
  `Courses_id` INT NOT NULL COMMENT '',
  `Students_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Courses_id`, `Students_id`)  COMMENT '',
  INDEX `fk_Courses_has_Students_Students1_idx` (`Students_id` ASC)  COMMENT '',
  INDEX `fk_Courses_has_Students_Courses1_idx` (`Courses_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`Courses_id`)
    REFERENCES `mydb`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
